package com.srv.vistas;

import com.srv.servicios.ReportePasajeReporteImpl;
import com.srv.servicios.ReportePasajeServicioI;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

public class ReporteFiltroPorRangoVista extends javax.swing.JInternalFrame {

    private ReportePasajeServicioI reporteServicio = new ReportePasajeReporteImpl();

    public ReporteFiltroPorRangoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jcFechaInicio = new rojeru_san.componentes.RSDateChooser();
        jcFechaFinal = new rojeru_san.componentes.RSDateChooser();

        setClosable(true);

        jButton1.setText("GENERAR REPORTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date fechaInicio = jcFechaInicio.getDatoFecha();
        Date fechaFinal = jcFechaFinal.getDatoFecha();
        if (fechaFinal != null && fechaInicio != null) {
            if (fechaInicio.before(fechaFinal) || fechaInicio.equals(fechaFinal)) {
                reporteServicio.generarReportePorRango(fechaInicio, fechaFinal);
            } else {
                JOptionPane.showMessageDialog(null, "Fecha Inicial mayor que la fecha Final, Corrija por favor");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Algun(os) campo(s) vacio(s)");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private rojeru_san.componentes.RSDateChooser jcFechaFinal;
    private rojeru_san.componentes.RSDateChooser jcFechaInicio;
    // End of variables declaration//GEN-END:variables
}
